name: flutter_pertama
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  onboarding: 3.1.0
  get: 4.6.5
  antdesign_icons: 0.0.3
  google_sign_in: 5.4.2
  firebase_core: 2.3.0
  firebase_auth: 4.1.4
  cloud_firestore: ^4.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

